### ISSUE TITLE
Remove Unmaintained "Remove Curse"-Action

### ISSUE THREAD

**Issue by Twonki** [sdras/awesome-actions#279]
The "Restrict Cursing Action" from https://github.com/sobolevn/restrict-cursing-action
seems to be unmaintained and broken. 

I reached out to the owner via [Issue](https://github.com/sobolevn/restrict-cursing-action/issues/41) which is not ... properly answered :) 

While my comment got redacted, it was from a local build of the repository, not from the (public) github action. 

The public github action fails, as there is no such (public) artifact 
![image](https://user-images.githubusercontent.com/19567117/70534842-d354b180-1b53-11ea-80ba-9ab4242f0457.png)

I'd therefore call this action unmaintained and would rather remove it from the list.

**Comment by php-coder** [comment]
@sobolevn JFYI

**Comment by sobolevn** [comment]
Yeap, it should probably be deleted. It was built as a joke / learning project. I am not using it anyway.

But, any help is appreciated if people want the project to live.

@Twonki considering your case, try to `@master` instead of `@latest`. It should solve 404, but not the incorrect behaviour. 

Thanks a lot for raising this!

**Comment by Twonki** [comment]
@sobolevn sorry i didn't want to sound salty :smile: 

I think it's a nice idea, and in general worth looking into. There are a lot of people swearing in commits, prs, code - and while I swear a lot in "real life" i think it does not belong anywhere in code. 

A lot of people have similar things in their code of conduct, so this seems to be a nice action to "enforce" it.
