### ISSUE TITLE
Think about merging policy of this repository

### ISSUE THREAD

**Issue by peaceiris** [sdras/awesome-actions#345]
See #321.

We can define our policy of this repository before adding fresh actions. This repository is *Awesome list*, not *new arrival list*. And, *a matter of main concern is maintainability*. The more new actions, the more burden for reviewing by maintainers of this repository. I started to worry about this at #321.

- How many stars?
- How long time has passed since an action repository started?
- Vote for a pull request?

## Examples

> The submitted project should be more than 30 days old and the repo should have at least 30 stars.
> [awesome-nodejs/contributing.md](https://github.com/sindresorhus/awesome-nodejs/blob/c975c07f6c738e4342f35bc51808ff11a976cea0/contributing.md)

> I will keep some pull requests open if I'm not sure whether those libraries are awesome, you could vote for them by adding 👍 to them. Pull requests will be merged when their votes reach 20.
> [vinta/awesome-python](https://github.com/vinta/awesome-python/tree/eb46fb3ed4f4688b9d06e4920f5ab53f94d4fd43)

**Comment by jessicalostinspace** [comment]
One of the most awesome things about this list is people can contribute to it to show others what is capable with actions in a succinct way, and allows them to get their work out in the public(so that people can star those repositories).

Actions are relatively new and still evolving, and aren’t necessarily as established as nodejs and python. It looks like a quick pass of links here with less than 30 stars would cut this repository down to half or less at this time. If the goal is to get those most starred repositories here, let’s write a scraper that sorts all GitHub Actions to replace this list. 

Another alternative is to write an action to scan all the repos in this list to check for the requirements that are set in the new policy :)

**Comment by peaceiris** [comment]
> One of the most awesome things about this list is people can contribute to it to show others what is capable with actions in a succinct way, and allows them to get their work out in the public(so that people can star those repositories).

[GitHub Actions Marketplace](https://github.com/marketplace?type=actions) already plays the role. This repository does not need to repeat the work of the official marketplace.

> Actions are relatively new and still evolving, and aren’t necessarily as established as nodejs and python. It looks like a quick pass of links here with less than 30 stars would cut this repository down to half or less at this time. If the goal is to get those most starred repositories here, let’s write a scraper that sorts all GitHub Actions to replace this list.
>
> Another alternative is to write an action to scan all the repos in this list to check for the requirements that are set in the new policy :)

Yes. This kind of action or tool is useful for all awesome lists, not only for this repository. Currently, I do not know actions or tools like that.

**Comment by gortcodes** [comment]
I'd recommend regular pruning over gating additions. Many of the actions in the list with a substantial number of stars did not start receiving stars until they were added to the list. 

@peaceiris as an example,  here are your 3 most popular contributions to the actions marketplace and to this list.  https://seladb.github.io/StarTrack-js/#/preload?r=peaceiris,actions-hugo&r=peaceiris,actions-mdbook&r=peaceiris,actions-gh-pages

They went relatively unnoticed until they were added to the list and would not have met your criteria for acceptance. After they, people started noticing that some of your contributions were _awesome actions._

To me this is indicative that people are more likely to find actions that fit their needs in this list than they are in the actions marketplace.

**Comment by peaceiris** [comment]
> The actions went relatively unnoticed until they were added to the list and would not have met your criteria for acceptance. After that, people started noticing that some of your contributions were awesome actions.

Yes, It looks like a possible story.

*A matter of main concern is maintainability*. The more new actions, the more burden for reviewing by maintainers of this repository. I started to worry about this at #321.

By the way, I think my case is a very special case. ([peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) was featured by GitHub, I contributed some problems related to Actions since beta v1, I wrote some posts, and so on.) I do not know whether users notice my projects on this awesome list, or not. It is thought that the influence is small.

**Comment by sdras** [comment]
Thanks for the concern, @peaceiris but I agree with @gortcodes' statement. I also don't want to gate people away from being able to contribute until their action is very well used, that's a surefire way to cut off an ecosystem and gatekeep. It's true that maintaining the repo takes time, which is why Gary and now Jessica are helping. I'd be up for periodic review with the two of them to prune out anything that isn't working well for the list.

**Comment by orozcoadrian** [comment]
my 2-cents: I agree more with @peaceiris but I appreciate the compromise concluded by the repo owner. Since "how awesome" this list is now depends on the periodic curation/pruning by contributors, can we add a prominent display of "last reviewed on [date]"? That will hopefully also inform users that this specific list performs its curation "after-the-fact" as opposed to as a gate before inclusion.

By "how awesome this list is" what I mean is "how closely does this list meet the spirit of ["awesome lists"](https://github.com/sindresorhus/awesome/blob/master/awesome.md#only-awesome-is-awesome)

I'd be happy to help by creating a small PR to just update that date whenever I see that a pruning PR has been merged.

**Comment by peaceiris** [comment]
I totally agree with @orozcoadrian :-)
